Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Models/AssignmentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Assignment2.Web.Models
{
    public class AssignmentViewModel
    {
        //======================== Properties ==============================================================================
        public int AssignmentId { get; set; }
        [Display(Name = "Assignment title")]
        [Required(ErrorMessage = "Title is required")]
        [MinLength(3, ErrorMessage = "The title needs at least 3 characters"), MaxLength(30, ErrorMessage = "The maximum length is 30 characters")]
        public string Title { get; set; }
        public string Description { get; set; }
        [Display(Name = "Submission date")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? SubDateTime { get; set; }
        [Display(Name ="Select course")]
        public IEnumerable<SelectListItem> Courses { get; set; }
        [Required(ErrorMessage = "Course is required")]
        public int? CourseId { get; set; }
        [Display(Name = "Select students")]
        public IEnumerable<SelectListItem> Students { get; set; }
        public List<int> StudentsId { get; set; }
        public bool FinalSubmit { get; set; }
        public IEnumerable<SelectListItem> ExistingStudents { get; set; }
        public List<int> ExistingStudentsId { get; set; }
    }
}

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Controllers/AssignmentController.cs
using System.Linq;
using System.Web.Mvc;
using Assignment2.Services;
using Assignment2.Entities;
using System.Net;
using System.Collections.Generic;
using PagedList;
using Assignment2.Web.Models;

namespace Assignment2.Web.Controllers
{
    public class AssignmentController : Controller
    {
        // GET: Assignment
        public ActionResult AllAssignments(string sort, string search, string currentFilter, int? page, int? pageSize)
        {
            AssignmentRepository assignmentRepository = new AssignmentRepository();
            var assignments = assignmentRepository.GetAll();
            assignmentRepository.Dispose();

            //Paging
            if (!string.IsNullOrWhiteSpace(search) || search == "")
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            int pSize = pageSize ?? 3;
            int pageNumber = page ?? 1;

            ViewBag.PageSize = new List<SelectListItem>()
            {
             new SelectListItem() { Value="3", Text= "3" },
             new SelectListItem() { Value="5", Text= "5" },
             new SelectListItem() { Value="10", Text= "10" },
             new SelectListItem() { Value="15", Text= "15" },
             new SelectListItem() { Value="25", Text= "25" },
             new SelectListItem() { Value="50", Text= "50" }
            };

            //searching
            if (!string.IsNullOrEmpty(search))
            {
                assignments = assignments.Where(x => x.Course.Title.ToUpper().Contains(search.ToUpper()) ||
                x.Title.ToUpper().Contains(search.ToUpper()) || x.Description.ToUpper().Contains(search.ToUpper()));
            }

            //sorting
            ViewBag.CourseTitle = string.IsNullOrEmpty(sort) ? "courseTitleDesc" : "";
            ViewBag.AssignmentTitle = sort == "assignmentTitleAsc" ? "assignmentTitleDesc" : "assignmentTitleAsc";
            ViewBag.Description = sort == "descriptionAsc" ? "descriptionDesc" : "descriptionAsc";
            ViewBag.SubmissionDate = sort == "submissionDateAsc" ? "submissionDateDesc" : "submissionDateAsc";

            switch (sort)
            {
                case "courseTitleDesc":
                    assignments = assignments.OrderByDescending(x => x.Course.Title);
                    break;
                case "assignmentTitleAsc":
                    assignments = assignments.OrderBy(x => x.Title);
                    break;
                case "assignmentTitleDesc":
                    assignments = assignments.OrderByDescending(x => x.Title);
                    break;
                case "descriptionAsc":
                    assignments = assignments.OrderBy(x => x.Description);
                    break;
                case "descriptionDesc":
                    assignments = assignments.OrderByDescending(x => x.Description);
                    break;
                case "submissionDateAsc":
                    assignments = assignments.OrderBy(x => x.SubDateTime);
                    break;
                case "submissionDateDesc":
                    assignments = assignments.OrderByDescending(x => x.SubDateTime);
                    break;
                default:
                    assignments = assignments.OrderBy(x => x.Title);
                    break;
            }

            ViewBag.CurrentFilter = search;
            ViewBag.CurrentSort = sort;
            ViewBag.CurrentPageSize = pSize;

            return View(assignments.ToPagedList(pageNumber, pSize));
        }

        // GET: TestAssignment/Details/5
        public ActionResult DetailsAssignment(int? id)
        {
            AssignmentRepository assignmentRepository = new AssignmentRepository();
            Assignment assignment = assignmentRepository.GetById(id);
            assignmentRepository.Dispose();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (assignment == null)
            {
                return HttpNotFound();
            }

            return View(assignment);

        }

        // GET: TestAssignment/Edit/5
        public ActionResult EditAssignment(int? id)
        {
            AssignmentRepository assignmentRepository = new AssignmentRepository();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assignment assignment = assignmentRepository.GetById(id);
            assignmentRepository.Dispose();

            if (assignment == null)
            {
                return HttpNotFound();
            }

            //Find Existing students
            StudentAssignmentRepository studentAssignmentRepository = new StudentAssignmentRepository();
            List<Student> existingStudents = studentAssignmentRepository.GetAll()
                                                    .Where(sa => sa.AssignmentId == id)
                                                    .Select(sa => sa.Student).ToList();
            studentAssignmentRepository.Dispose();

            //Find not existing students which have assigned in the assignment's course
            int? courseId = assignment.CourseId;
            List<Student> studentsPerCourse = new List<Student>();
            if (courseId != null)
            {
                CourseRepository courseRepository = new CourseRepository();
                studentsPerCourse = courseRepository.GetById(courseId).StudentCourses
                                                       .Select(sc => sc.Student).ToList();
                courseRepository.Dispose();

                foreach (Student student in existingStudents)
                {
                    Student findStudent = studentsPerCourse.Find(s => s.StudentId == student.StudentId);
                    studentsPerCourse.Remove(findStudent);
                }
            }

            //Create assignmentViewModel
            AssignmentViewModel assignmentViewModel = new AssignmentViewModel()
            {
                AssignmentId = assignment.AssignmentId,
                Description = assignment.Description,
                SubDateTime = assignment.SubDateTime,
                Title = assignment.Title,
                CourseId = assignment.CourseId,
                Students = Methods.CreateSelectListOfStudents(studentsPerCourse),
                ExistingStudents = Methods.CreateSelectListOfStudents(existingStudents)
            };

            return View(assignmentViewModel);
        }

        // POST: TestAssignment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAssignment([Bind(Include = "AssignmentId,Title,Description,SubDateTime,CourseId,ExistingStudentsId,StudentsId")] AssignmentViewModel assignmentViewModel)
        {
            if (ModelState.IsValid)
            {
                //Create Assignment
                Assignment assignment = new Assignment()
                {
                    AssignmentId = assignmentViewModel.AssignmentId,
                    Title = assignmentViewModel.Title,
                    Description = assignmentViewModel.Description,
                    CourseId = assignmentViewModel.CourseId,
                    SubDateTime = assignmentViewModel.SubDateTime
                };

                //Insert assignment
                AssignmentRepository assignmentRepository = new AssignmentRepository();
                assignmentRepository.Update(assignment);
                assignmentRepository.Dispose();

                //Update the realation student-assignment
                StudentAssignmentRepository studentAssignmentRepository = new StudentAssignmentRepository();
                //Remove students from assignments
                if (assignmentViewModel.ExistingStudentsId != null)
                {
                    List<StudentAssignment> allStudentAssignments = studentAssignmentRepository.GetAll().ToList();
                    foreach (int studentId in assignmentViewModel.ExistingStudentsId)
                    {
                        StudentAssignment studentAssignment = allStudentAssignments.Find(sa => sa.StudentId == studentId);
                        studentAssignmentRepository.Delete(studentAssignment);
                    }
                }
                //Add student into assignments
                if (assignmentViewModel.StudentsId != null)
                {
                    foreach (int studentId in assignmentViewModel.StudentsId)
                    {
                        StudentAssignment studentAssignment = new StudentAssignment()
                        {
                            StudentId = studentId,
                            AssignmentId = assignment.AssignmentId
                        };
                        studentAssignmentRepository.Insert(studentAssignment);
                    }
                }
                studentAssignmentRepository.Dispose();

                return RedirectToAction("AllAssignments");
            }

            //Find Existing students
            StudentAssignmentRepository studentAssignmentRepository2 = new StudentAssignmentRepository();
            List<Student> existingStudents = studentAssignmentRepository2.GetAll()
                                                    .Where(sa => sa.AssignmentId == assignmentViewModel.AssignmentId)
                                                    .Select(sa => sa.Student).ToList();
            studentAssignmentRepository2.Dispose();

            //Find not existing students which have assigned in the assignment's course
            int? courseId = assignmentViewModel.CourseId;

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Assignment/AllAssignments.cshtml
@model PagedList.IPagedList<Assignment2.Entities.Assignment>
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "All Assignments";
}

<h2>All assignments</h2>

@using (Html.BeginForm("AllAssignments", "Assignment", FormMethod.Get, new { id = "form" }))
{
    <div class="d-inline-block mb-1 w-100">
        <div class="float-left d-inline">
            @Html.ActionLink("Insert new assignment", "CreateAssignment", null, new { @class = "btn btn-primary" })
        </div>
        <div class="float-right d-inline">
            @Html.Label("search", "Find by title or by description :", null)
            @Html.TextBox("search", ViewBag.CurrentFilter as string, new { @class = "searchBar", @placeholder = "Search..." })<input type="submit" value="Search" class="btn-search" />
        </div>
    </div>

    string currentSort = ViewBag.CurrentSort;
    @Html.TextBox("sort", currentSort, new { type = "hidden", @class = "form-control" })

    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Course title", "AllAssignments", new { sort = ViewBag.CourseTitle, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
            </th>
            <th>
                @Html.ActionLink("Assignment title", "AllAssignments", new { sort = ViewBag.AssignmentTitle, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
            </th>
            <th>
                @Html.ActionLink("Description", "AllAssignments", new { sort = ViewBag.Description, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
            </th>
            <th>
                @Html.ActionLink("Submission date", "AllAssignments", new { sort = ViewBag.SubmissionDate, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
            </th>
            <th></th>
        </tr>
        @foreach (var assignment in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => assignment.Course.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => assignment.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => assignment.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => assignment.SubDateTime)
                </td>
                <td class="text-right">
                    @Html.ActionLink("Edit marks", "Marks", new { id = assignment.AssignmentId }, new { @class = "btn btn-dark" })
                    @Html.ActionLink("Edit", "EditAssignment", new { id = assignment.AssignmentId }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Details", "DetailsAssignment", new { id = assignment.AssignmentId }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Delete", "DeleteAssignment", new { id = assignment.AssignmentId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </table>

    <div class="float-left">
        @{ string cps = Convert.ToString(ViewBag.CurrentPageSize); }
        Items per page: @Html.DropDownList("pageSize", cps)
        @Html.PagedListPager(Model, page => Url.Action("AllAssignments", new { page, sort = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize }))

        @{string currentfilter = ViewBag.CurrentFilter;}
        @Html.TextBox("currentFilter", currentfilter, new { type = "hidden", @class = "form-control" })
    </div>
}

<script src="~/Content/MyJs/GeneralJs.js"></script>

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Assignment/CreateAssignment.cshtml
@model Assignment2.Web.Models.AssignmentViewModel

@{
    ViewBag.Title = "Create Assignment";
}
<h2>Assignment</h2>


@using (Html.BeginForm("CreateAssignment", "Assignment", FormMethod.Post, new { id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Insert new assignment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Courses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CourseId, Model.Courses, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.CourseId != null)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Students, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.ListBoxFor(model => model.StudentsId, Model.Students, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StudentsId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        @Html.TextBox("FinalSubmit", true, new { type = "hidden", @class = "form-control" })

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" /> @Html.ActionLink("Back to assignments", "AllAssignments", null, new { @class = "btn btn-info" })

            </div>
        </div>
    </div>
}

<script>
    (function () {
        document.getElementById("CourseId").addEventListener("change", change);
        document.getElementById("FinalSubmit").value = true;
    })();

    function change() {
        document.getElementById("FinalSubmit").value = false;
        document.getElementById("form").submit();
    }
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Assignment/DeleteAssignment.cshtml
@model Assignment2.Entities.Assignment

@{
    ViewBag.Title = "Delete Assignment";
}

<h2>Delete assignment</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubDateTime)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to assignments", "AllAssignments", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Assignment/DetailsAssignment.cshtml
@model Assignment2.Entities.Assignment

@{
    ViewBag.Title = "Details Assignment";
}

<link href="~/Content/MyCss/DetailLinks.css" rel="stylesheet" />

<h2>Assignment details</h2>

<div>
    <h4>@Html.DisplayFor(model => model.Title)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.ActionLink(Model.Course.Title, "DetailsCourse", "Course", new { id = Model.CourseId }, new { @class = "myLinks" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubDateTime)
        </dd>

        <dt>
            Number of students
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentAssignments.Count)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditAssignment", new { id = Model.AssignmentId }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Back to assignments", "AllAssignments", null, new { @class = "btn btn-info" })
</p>

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Assignment/EditAssignment.cshtml
@model Assignment2.Web.Models.AssignmentViewModel

@{
    ViewBag.Title = "Edit Assignment";
}

<h2>Edit assignment</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Assignment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AssignmentId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.ExistingStudents.Count() > 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.ExistingStudents, "Remove students", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.ListBoxFor(model => model.ExistingStudentsId, Model.ExistingStudents, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExistingStudentsId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        @if (Model.Students.Count() > 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Students, "Add students", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.ListBoxFor(model => model.StudentsId, Model.Students, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StudentsId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <input type="text" name="CourseId" value=@Model.CourseId hidden />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" /> @Html.ActionLink("Back to assignments", "AllAssignments", null, new { @class = "btn btn-info" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Assignment/Marks.cshtml
@model Assignment2.Web.Models.StudentAssignmentsViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Edit marks for @Model.StudentAssignments[0].Assignment.Title</h2>
        <hr />
        <h4>Students</h4>
        <div class="form-group">
            <table class="table">
                <tr>
                    <th>
                        First name
                    </th>
                    <th>
                        Last name
                    </th>
                    <th>
                        Oral mark
                    </th>
                    <th>
                        Writing mark
                    </th>
                </tr>
                @for (int j = 0; j < Model.StudentAssignments.Count(); j++)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(model => model.StudentAssignments[j].Student.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.StudentAssignments[j].Student.LastName)
                        </td>
                        <td>
                            @Html.EditorFor(model => model.StudentAssignments[j].OralMark, new { htmlAttributes = new { @class = "form-control"} })
                            @Html.ValidationMessageFor(model => model.StudentAssignments[j].OralMark, "", new { @class = "text-danger" })
                        </td>
                        <td>
                            @Html.EditorFor(model => model.StudentAssignments[j].WritingMark, new { htmlAttributes = new { @class = "form-control"} })
                            @Html.ValidationMessageFor(model => model.StudentAssignments[j].WritingMark, "", new { @class = "text-danger" })
                        </td>

                        <td hidden>
                            <input type="number" name="StudentAssignments[@j].StudentAssignmentId" value=@Model.StudentAssignments[j].StudentAssignmentId hidden />
                        </td>
                    </tr>
                }
            </table>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" /> @Html.ActionLink("Back to assignments", "AllAssignments", null, new { @class = "btn btn-info" })
            </div>
        </div>
    </div>
}

<script>

</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}