Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Models/TrainerViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace Assignment2.Web.Models
{
    public class TrainerViewModel
    {
        //======================== Properties ================================================
        public int TrainerId { get; set; }
        [Required(ErrorMessage = "First name is required")]
        [Display(Name = "First name")]
        [MinLength(3, ErrorMessage = "The minimum length is 3 characters"), MaxLength(30, ErrorMessage = "The maximum length is 30 characters")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last name is required")]
        [Display(Name = "Last name")]
        [MinLength(3, ErrorMessage = "The minimum length is 3 characters"), MaxLength(30, ErrorMessage = "The maximum length is 30 characters")]
        public string LastName { get; set; }
        public string Subject { get; set; }
        [Display(Name = "Trainer photo")]
        public string PhotoUrl { get; set; }
        [Display(Name = "Trainer photo")]
        public HttpPostedFileBase ImageFile { get; set; }
        [Display(Name = "Courses")]
        public IEnumerable<SelectListItem> Courses { get; set; }
        public List<int> CoursesId { get; set; }
        public IEnumerable<SelectListItem> ExistingCourses { get; set; }
        public List<int> ExistingCoursesCoursesId { get; set; }
    }
}

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Controllers/TrainerController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Assignment2.Services;
using Assignment2.Entities;
using System.Collections.Generic;
using PagedList;
using Assignment2.Web.Models;
using System.IO;
using System;

namespace Assignment2.Web.Controllers
{
    public class TrainerController : Controller
    {
        // GET: Trainer
        public ActionResult AllTrainers(string sort, string search, string currentFilter, int? page, int? pageSize)
        {
            TrainerRepository trainerRepository = new TrainerRepository();
            var trainers = trainerRepository.GetAll();
            trainerRepository.Dispose();

            //============================================== Paging ========================================================
            if (!string.IsNullOrWhiteSpace(search) || search == "")
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }
            int pSize = pageSize ?? 3;
            int pageNumber = page ?? 1;

            ViewBag.PageSize = new List<SelectListItem>()
            {
             new SelectListItem() { Value="3", Text= "3" },
             new SelectListItem() { Value="5", Text= "5" },
             new SelectListItem() { Value="10", Text= "10" },
             new SelectListItem() { Value="15", Text= "15" },
             new SelectListItem() { Value="25", Text= "25" },
             new SelectListItem() { Value="50", Text= "50" }
            };

            //============================================== searching =====================================================
            if (!string.IsNullOrEmpty(search))
            {
                trainers = trainers.Where(x => x.FirstName.ToUpper().Contains(search.ToUpper()) ||
                x.LastName.ToUpper().Contains(search.ToUpper()) ||
                x.Subject.ToUpper().Contains(search.ToUpper()));
            }

            //============================================== sorting =======================================================
            ViewBag.FirstName = string.IsNullOrEmpty(sort) ? "firstNameDesc" : "";
            ViewBag.LastName = sort == "lastNameAsc" ? "lastNameDesc" : "lastNameAsc";
            ViewBag.Subject = sort == "subjectAsc" ? "subjectDesc" : "subjectAsc";


            switch (sort)
            {
                case "firstNameDesc":
                    trainers = trainers.OrderByDescending(x => x.FirstName);
                    break;
                case "lastNameAsc":
                    trainers = trainers.OrderBy(x => x.LastName);
                    break;
                case "lastNameDesc":
                    trainers = trainers.OrderByDescending(x => x.LastName);
                    break;
                case "subjectAsc":
                    trainers = trainers.OrderBy(x => x.Subject);
                    break;
                case "subjectDesc":
                    trainers = trainers.OrderByDescending(x => x.Subject);
                    break;
                default:
                    trainers = trainers.OrderBy(x => x.FirstName);
                    break;
            }

            ViewBag.CurrentFilter = search;
            ViewBag.CurrentSort = sort;
            ViewBag.CurrentPageSize = pSize;

            return View(trainers.ToPagedList(pageNumber, pSize));
        }

        // GET: TestTrainer/Details/5
        public ActionResult DetailsTrainer(int? id)
        {
            TrainerRepository trainerRepository = new TrainerRepository();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = trainerRepository.GetById(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            trainerRepository.Dispose();

            return View(trainer);
        }

        // GET: TestTrainer/Edit/5
        public ActionResult EditTrainer(int? id)
        {
            TrainerRepository trainerRepository = new TrainerRepository();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = trainerRepository.GetById(id);
            trainerRepository.Dispose();

            if (trainer == null)
            {
                return HttpNotFound();
            }

            //Get all Courses
            CourseRepository courseRepository = new CourseRepository();
            List<Course> courses = courseRepository.GetAll().ToList();
            courseRepository.Dispose();

            //Get CourseId where trainerId is the id of the trainer that we want to edit
            TrainerCourseRepository trainerCourseRepository = new TrainerCourseRepository();
            IEnumerable<int> coursesId = trainerCourseRepository.GetAll()
                                                        .Where(tc => tc.TrainerId == id)
                                                        .Select(tc => tc.CourseId);
            trainerCourseRepository.Dispose();

            //Create a list with courses which have assigned to the trainer
            List<Course> existingCourses = new List<Course>();
            foreach (int courseId in coursesId)
            {
                Course course = courses.FirstOrDefault(c => c.CourseId == courseId);
                existingCourses.Add(course);
                courses.Remove(course);
            }

            //Create trainerViewModel
            TrainerViewModel trainerViewModel = new TrainerViewModel()
            {
                TrainerId = trainer.TrainerId,
                FirstName = trainer.FirstName,
                LastName = trainer.LastName,
                Subject = trainer.Subject,
                PhotoUrl = trainer.PhotoUrl,
                ExistingCourses = Methods.CreateSelectListOfCourses(existingCourses),
                Courses = Methods.CreateSelectListOfCourses(courses)
            };

            return View(trainerViewModel);
        }

        // POST: TestTrainer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditTrainer([Bind(Include = "TrainerId,FirstName,LastName,Subject,PhotoUrl,ImageFile,ExistingCoursesCoursesId,CoursesId")] TrainerViewModel trainerViewModel)
        {
            if (ModelState.IsValid)
            {
                //Save upload file
                if (trainerViewModel.ImageFile != null)
                {
                    string extention = Path.GetExtension(trainerViewModel.ImageFile.FileName);
                    string fileName = trainerViewModel.FirstName + trainerViewModel.LastName + DateTime.Now.ToString("yyyyMMddmmss") + extention;
                    trainerViewModel.PhotoUrl = "../../Content/Trainers_Images/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Content/Trainers_Images/"), fileName);
                    trainerViewModel.ImageFile.SaveAs(fileName);
                }

                //Update trainerCourse
                if (trainerViewModel.CoursesId != null || trainerViewModel.ExistingCoursesCoursesId != null)
                {
                    TrainerCourseRepository trainerCourseRepository = new TrainerCourseRepository();
                    //Delete trainerCourse
                    if (trainerViewModel.ExistingCoursesCoursesId != null)
                    {
                        List<TrainerCourse> trainerCourses = trainerCourseRepository.GetAll()
                                                            .Where(tc => tc.TrainerId == trainerViewModel.TrainerId).ToList();
                        foreach (int id in trainerViewModel.ExistingCoursesCoursesId)
                        {
                            TrainerCourse trainerCourse = trainerCourses.FirstOrDefault(tc => tc.CourseId == id);
                            trainerCourseRepository.Delete(trainerCourse);
                        }
                    }
                    if (trainerViewModel.CoursesId != null)
                    {
                        //Insert trainerCourse
                        foreach (int id in trainerViewModel.CoursesId)
                        {
                            TrainerCourse trainerCourse = new TrainerCourse()
                            {
                                TrainerId = trainerViewModel.TrainerId,
                                CourseId = id
                            };
                            trainerCourseRepository.Insert(trainerCourse);
                        }
                    }

                    trainerCourseRepository.Dispose();
                }

                //Create trainer and update
                Trainer trainer = new Trainer()
                {
                    TrainerId = trainerViewModel.TrainerId,
                    FirstName = trainerViewModel.FirstName,
                    LastName = trainerViewModel.LastName,
                    PhotoUrl = trainerViewModel.PhotoUrl,
                    Subject = trainerViewModel.Subject
                };

                TrainerRepository trainerRepository = new TrainerRepository();
                trainerRepository.Update(trainer);
                trainerRepository.Dispose();

                return RedirectToAction("AllTrainers");
            }
            return View(trainerViewModel);
        }

        // GET: TestTrainer/Create
        public ActionResult CreateTrainer()
        {
            //Get all courses
            CourseRepository courseRepository = new CourseRepository();
            IEnumerable<Course> allCourses = courseRepository.GetAll();
            courseRepository.Dispose();

            //Create TrainerViewModel

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Trainer/AllTrainers.cshtml
@model PagedList.IPagedList<Assignment2.Entities.Trainer>
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "All Trainers";
}

<h2>All Trainers</h2>

@using (Html.BeginForm("AllTrainers", "Trainer", FormMethod.Get, new { id = "form" }))
{
    <div class="d-inline-block mb-1 w-100">
        <div class="float-left d-inline">
            @Html.ActionLink("Insert new trainer", "CreateTrainer", null, new { @class = "btn btn-primary" })
        </div>
        <div class="float-right d-inline">
            @Html.Label("search", "Find by first name, last name or subject :", null)
            @Html.TextBox("search", ViewBag.CurrentFilter as string, new { @class = "searchBar", @placeholder = "Search..." })<input type="submit" value="Search" class="btn-search" />
        </div>
    </div>

    string currentSort = ViewBag.CurrentSort;
    @Html.TextBox("sort", currentSort, new { type = "hidden", @class = "form-control" })

    <table class="table">
        <tr>
            <th>
                Trainer photo
            </th>
            <th>
                @Html.ActionLink("First name", "AllTrainers", new { sort = ViewBag.FirstName, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
            </th>
            <th>
                @Html.ActionLink("Last name", "AllTrainers", new { sort = ViewBag.LastName, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
            </th>
            <th>
                @Html.ActionLink("Subject", "AllTrainers", new { sort = ViewBag.Subject, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
            </th>
            <th></th>
        </tr>
        @foreach (var trainer in Model)
        {
            <tr>
                <td>
                    <img src="@Html.DisplayFor(x => trainer.PhotoUrl)" width="80" alt="Photo of @Html.DisplayFor(x => trainer.FirstName) @Html.DisplayFor(x => trainer.LastName)" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => trainer.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => trainer.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => trainer.Subject)
                </td>
                <td class="text-right">
                    @Html.ActionLink("Edit", "EditTrainer", new { id = trainer.TrainerId }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Details", "DetailsTrainer", new { id = trainer.TrainerId }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Delete", "DeleteTrainer", new { id = trainer.TrainerId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </table>

    <div class="float-left">
        @{ string cps = Convert.ToString(ViewBag.CurrentPageSize); }
        Items per page: @Html.DropDownList("pageSize", cps)
        @Html.PagedListPager(Model, page => Url.Action("AllTrainers", new { page, sort = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize }))

        @{string currentfilter = ViewBag.CurrentFilter;}
        @Html.TextBox("currentFilter", currentfilter, new { type = "hidden", @class = "form-control" })
    </div>
}

<script src="~/Content/MyJs/GeneralJs.js"></script>

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Trainer/CreateTrainer.cshtml
@model Assignment2.Web.Models.TrainerViewModel

@{
    ViewBag.Title = "Create Trainer";
}

<h2>Trainer</h2>


@using (Html.BeginForm("CreateTrainer", "Trainer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Insert new trainer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" class="btn btn-light" accept="image/*" />
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Courses, "Assign courses", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.CoursesId, Model.Courses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoursesId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" /> @Html.ActionLink("Back to trainers", "AllTrainers", null, new { @class = "btn btn-info" })

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Trainer/DeleteTrainer.cshtml
@model Assignment2.Entities.Trainer

@{
    ViewBag.Title = "Delete Trainer";
}

<h2>Delete Trainer</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.PhotoUrl)" width="80" alt="Photo of @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> @Html.ActionLink("Back to trainers", "AllTrainers", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Trainer/DetailsTrainer.cshtml
@model Assignment2.Entities.Trainer

@{
    ViewBag.Title = "Details Trainer";
}

<link href="~/Content/MyCss/DetailLinks.css" rel="stylesheet" />

<h2>Trainer details</h2>

<div>
    <h4>@Model.FirstName @Model.LastName</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(x => Model.PhotoUrl)" width="80" alt="Photo of @Html.DisplayFor(x => Model.FirstName) @Html.DisplayFor(x => Model.LastName)" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            Courses
        </dt>

        <dd>
            <ul>
                @{
                    foreach (var course in Model.TrainerCourses)
                    {
                        <li>@Html.ActionLink(course.Course.Title, "DetailsCourse", "Course", new { id = course.CourseId }, new { @class = "myLinks" })</li>
                    }
                }
            </ul>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditTrainer", new { id = Model.TrainerId }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Back to trainers", "AllTrainers", null, new { @class = "btn btn-info" })
</p>

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/Trainer/EditTrainer.cshtml
@model Assignment2.Web.Models.TrainerViewModel

@{
    ViewBag.Title = "Edit Trainer";
}

<h2>Edit Trainer</h2>


@using (Html.BeginForm("EditTrainer", "Trainer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Model.FirstName @Model.LastName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TrainerId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" accept="image/*" class="btn btn-light" />
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.ExistingCourses.Count() > 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.ExistingCoursesCoursesId, "Remove courses", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.ListBoxFor(model => model.ExistingCoursesCoursesId, Model.ExistingCourses, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExistingCoursesCoursesId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        @if (Model.Courses.Count() > 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.CoursesId, "Assign courses", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.ListBoxFor(model => model.CoursesId, Model.Courses, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CoursesId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <input type="text" name="PhotoUrl" value=@Model.PhotoUrl hidden />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" /> @Html.ActionLink("Back to trainers", "AllTrainers", null, new { @class = "btn btn-info" })

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}