Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Controllers/CourseController.cs
using System.Linq;
using System.Web.Mvc;
using Assignment2.Services;
using Assignment2.Entities;
using System.Net;
using PagedList;
using System.Collections.Generic;
using System;
using Assignment2.Web.Models;

namespace Assignment2.Web.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course
        public ActionResult AllCourses(string sort, string search, string currentFilter, int? page, int? pageSize)
        {
            CourseRepository courseRepository = new CourseRepository();
            var courses = courseRepository.GetAll();
            courseRepository.Dispose();


            //============================================== Paging ========================================================
            if (!string.IsNullOrWhiteSpace(search) || search == "")
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            int pSize = pageSize ?? 3;
            int pageNumber = page ?? 1;

            ViewBag.PageSize = new List<SelectListItem>()
            {
             new SelectListItem() { Value="3", Text= "3" },
             new SelectListItem() { Value="5", Text= "5" },
             new SelectListItem() { Value="10", Text= "10" },
             new SelectListItem() { Value="15", Text= "15" },
             new SelectListItem() { Value="25", Text= "25" },
             new SelectListItem() { Value="50", Text= "50" }
            };
            //============================================== searching =====================================================
            if (!string.IsNullOrEmpty(search))
            {
                courses = courses.Where(c => c.Title.ToUpper().Contains(search.ToUpper()) || c.Type.ToUpper().Contains(search.ToUpper()));
            }

            //============================================== sorting =======================================================
            ViewBag.CourseTitle = string.IsNullOrEmpty(sort) ? "courseTitleDesc" : "";
            ViewBag.Stream = sort == "streamAsc" ? "streamDesc" : "streamAsc";
            ViewBag.Type = sort == "typeAsc" ? "typeDesc" : "typeAsc";
            ViewBag.StartDate = sort == "startDateAsc" ? "startDateDesc" : "startDateAsc";
            ViewBag.EndDate = sort == "endDateAsc" ? "endDateDesc" : "endDateAsc";

            switch (sort)
            {
                case "courseTitleDesc":
                    courses = courses.OrderByDescending(x => x.Title);
                    break;
                case "streamAsc":
                    courses = courses.OrderBy(x => x.Stream);
                    break;
                case "streamDesc":
                    courses = courses.OrderByDescending(x => x.Stream);
                    break;
                case "typeAsc":
                    courses = courses.OrderBy(x => x.Type);
                    break;
                case "typeDesc":
                    courses = courses.OrderByDescending(x => x.Type);
                    break;
                case "startDateAsc":
                    courses = courses.OrderBy(x => x.StartDate);
                    break;
                case "startDateDesc":
                    courses = courses.OrderByDescending(x => x.StartDate);
                    break;
                case "endDateAsc":
                    courses = courses.OrderBy(x => x.EndDate);
                    break;
                case "endDateDesc":
                    courses = courses.OrderByDescending(x => x.EndDate);
                    break;
                default:
                    courses = courses.OrderBy(x => x.Title);
                    break;
            }

            ViewBag.CurrentSort = sort;
            ViewBag.CurrentFilter = search;
            ViewBag.CurrentPageSize = pSize;

            return View(courses.ToPagedList(pageNumber, pSize));
        }

        // GET: TestCourse/Details/5
        public ActionResult DetailsCourse(int? id)
        {
            CourseRepository courseRepository = new CourseRepository();
            Course course = courseRepository.GetById(id);
            courseRepository.Dispose();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (course == null)
            {
                return HttpNotFound();
            }

            return View(course);

        }

        // GET: TestCourse/Edit/5
        public ActionResult EditCourse(int? id)
        {
            CourseRepository courseRepository = new CourseRepository();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = courseRepository.GetById(id);
            courseRepository.Dispose();

            if (course == null)
            {
                return HttpNotFound();
            }

            StudentCourseRepository studentCourseRepository = new StudentCourseRepository();
            var studentsCourses = studentCourseRepository.GetAll().Where(c => c.CourseId == id);
            studentCourseRepository.Dispose();
            IEnumerable<int> selectedStudentsId = studentsCourses.Select(sc => sc.StudentId);

            TrainerCourseRepository trainerCourseRepository = new TrainerCourseRepository();
            var trainersCourses = trainerCourseRepository.GetAll().Where(tc => tc.CourseId == id);
            trainerCourseRepository.Dispose();
            IEnumerable<int> selectedTrainersId = trainersCourses.Select(tc => tc.TrainerId);

            StudentRepository studentRepository = new StudentRepository();
            List<Student> allStudents = studentRepository.GetAll().ToList();
            studentRepository.Dispose();

            TrainerRepository trainerRepository = new TrainerRepository();
            List<Trainer> allTrainers = trainerRepository.GetAll().ToList();
            trainerRepository.Dispose();

            //find all students which are included in this course and remove them from the list allStudents
            List<Student> existingStudents = new List<Student>();
            foreach (var studentId in selectedStudentsId)
            {
                Student selectedStudent = allStudents.First(s => s.StudentId == studentId);
                existingStudents.Add(selectedStudent);
                allStudents.Remove(selectedStudent);
            }

            //find all trainers which are included in this course and remove them from the list allTrainers
            List<Trainer> existingTrainers = new List<Trainer>();
            foreach (var trainerId in selectedTrainersId)
            {
                Trainer selectedTrainer = allTrainers.First(t => t.TrainerId == trainerId);
                existingTrainers.Add(selectedTrainer);
                allTrainers.Remove(selectedTrainer);
            }

            CourseViewModel courseViewModel = new CourseViewModel()
            {
                CourseId = (int)id,
                Stream = course.Stream,
                Type = course.Type,
                Title = course.Title,
                StartDate = course.StartDate,
                EndDate = course.EndDate,
                TuitionFees = course.CourseFees,
                StudentsForAddition = Methods.CreateSelectListOfStudents(allStudents),
                TrainersForAddition = Methods.CreateSelectListOfTrainers(allTrainers),
                StudentsForSubtraction = Methods.CreateSelectListOfStudents(existingStudents),
                TrainersForSubtraction = Methods.CreateSelectListOfTrainers(existingTrainers)
            };

            return View(courseViewModel);
        }

        // POST: TestCourse/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCourse(
            [Bind(Include = "CourseId,Title,Stream,Type,StartDate,EndDate,TuitionFees,TrainersForSubtractionId,TrainersForAdditionId,StudentsForSubtractionId,StudentsForAdditionId")]
        CourseViewModel courseViewModel)
        {
            if (ModelState.IsValid)
            {
                if (courseViewModel.TrainersForSubtractionId != null)
                {
                    TrainerCourseRepository trainerCourseRepository = new TrainerCourseRepository();
                    var trainersCourses = trainerCourseRepository.GetAll().Where(tc => tc.CourseId == courseViewModel.CourseId);
                    foreach (var id in courseViewModel.TrainersForSubtractionId)
                    {
                        TrainerCourse trainerCourse = trainersCourses.FirstOrDefault(tc => tc.TrainerId == Convert.ToInt32(id));
                        trainerCourseRepository.Delete(trainerCourse);
                    }
                    trainerCourseRepository.Dispose();
                }

                if (courseViewModel.TrainersForAdditionId != null)
                {
                    TrainerCourseRepository trainerCourseRepository = new TrainerCourseRepository();
                    foreach (var id in courseViewModel.TrainersForAdditionId)
                    {
                        TrainerCourse trainerCourse = new TrainerCourse()
                        {
                            CourseId = courseViewModel.CourseId,
                            TrainerId = Convert.ToInt32(id)
                        };
                        trainerCourseRepository.Insert(trainerCourse);
                    }
                    trainerCourseRepository.Dispose();
                }

                if (courseViewModel.StudentsForSubtractionId != null)
                {
                    StudentCourseRepository studentCourseRepository = new StudentCourseRepository();

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Controllers/TrainersPerCourseController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Assignment2.Services;
using PagedList;

namespace Assignment2.Web.Controllers
{
    public class TrainersPerCourseController : Controller
    {
        // GET: TrainersPerCourse
        public ActionResult AllTrainerCourse(string sort, string search, string currentFilter, int? page, int? pageSize)
        {
            TrainerCourseRepository trainerCourseRepository = new TrainerCourseRepository();
            var trainerCourse = trainerCourseRepository.GetAll();
            trainerCourseRepository.Dispose();

            //============================================== Paging ========================================================
            if (!string.IsNullOrWhiteSpace(search) || search == "")
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }
            int pSize = pageSize ?? 3;
            int pageNumber = page ?? 1;

            ViewBag.PageSize = new List<SelectListItem>()
            {
             new SelectListItem() { Value="3", Text= "3" },
             new SelectListItem() { Value="5", Text= "5" },
             new SelectListItem() { Value="10", Text= "10" },
             new SelectListItem() { Value="15", Text= "15" },
             new SelectListItem() { Value="25", Text= "25" },
             new SelectListItem() { Value="50", Text= "50" }
            };

            //============================================== searching =====================================================
            if (!string.IsNullOrEmpty(search))
            {
                trainerCourse = trainerCourse.Where(x => x.Course.Title.ToUpper().Contains(search.ToUpper()) ||
                x.Trainer.FirstName.ToUpper().Contains(search.ToUpper()) || x.Trainer.LastName.ToUpper().Contains(search.ToUpper()));
            }

            //============================================== sorting =======================================================
            ViewBag.CourseTitle = string.IsNullOrEmpty(sort) ? "courseTitleDesc" : "";

            switch (sort)
            {
                case "courseTitleDesc":
                    trainerCourse = trainerCourse.OrderByDescending(x => x.Course.Title);
                    break;
                default:
                    trainerCourse = trainerCourse.OrderBy(x => x.Course.Title);
                    break;
            }

            ViewBag.CurrentFilter = search;
            ViewBag.CurrentSort = sort;
            ViewBag.CurrentPageSize = pSize;

            return View(trainerCourse.GroupBy(x => x.Course).ToPagedList(pageNumber, pSize));
        }
    }
}

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/TrainersPerCourse/AllTrainerCourse.cshtml
@model PagedList.IPagedList<IEnumerable<Assignment2.Entities.TrainerCourse>>
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/MyCss/DetailLinks.css" rel="stylesheet" />

@{
    ViewBag.Title = "AllTrainersCourses";
}

<h2>All trainers per course</h2>

@using (Html.BeginForm("AllTrainerCourse", "TrainersPerCourse", FormMethod.Get, new { id = "form" }))
{
    <div class="d-inline-block mb-1 w-100">
        <div class="float-right d-inline">
            @Html.Label("search", "Find by title, first name or last name :", null)
            @Html.TextBox("search", ViewBag.CurrentFilter as string, new { @class = "searchBar", @placeholder = "Search..." })<input type="submit" value="Search" class="btn-search" />
        </div>
    </div>

    string currentSort = ViewBag.CurrentSort;
    @Html.TextBox("sort", currentSort, new { type = "hidden", @class = "form-control" })

    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Course title", "AllTrainerCourse", new { sort = ViewBag.CourseTitle, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
            </th>
            <th>
                Trainers
            </th>
        </tr>
        @foreach (var trainerCourse in Model)
        {
            foreach (var course in trainerCourse.GroupBy(x => x.Course))
            {
                <tr>
                    <td>
                        @Html.ActionLink(course.Key.Title, "DetailsCourse", "Course", new { id = course.Key.CourseId }, new { @class = "myLinks" })
                    </td>
                    <td>
                        <ol>
                            @foreach (var trainerCourseOfcourse in course)
                            {
                                <li>
                                    <img src="@trainerCourseOfcourse.Trainer.PhotoUrl" width="20" height="20" alt="Alternate Text" />
                                    @Html.ActionLink(trainerCourseOfcourse.Trainer.FirstName + " " + trainerCourseOfcourse.Trainer.LastName, "DetailsTrainer", "Trainer", new { id = trainerCourseOfcourse.Trainer.TrainerId }, new { @class = "myLinks" })
                                </li>
                            }
                        </ol>
                    </td>
                </tr>
            }
        }
    </table>

    <div class="float-left">
        @{ string cps = Convert.ToString(ViewBag.CurrentPageSize); }
        Items per page: @Html.DropDownList("pageSize", cps)
        @Html.PagedListPager(Model, page => Url.Action("AllTrainerCourse", new { page, sort = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize }))

        @{string currentfilter = ViewBag.CurrentFilter;}
        @Html.TextBox("currentFilter", currentfilter, new { type = "hidden", @class = "form-control" })
    </div>
}

<script src="~/Content/MyJs/GeneralJs.js"></script>

Koutsogiorgos_Evangelos_Assignment_2/Assignment2.Web/Views/TrainersPerCourse/AllTrainersCourses.cshtml
@model IEnumerable<Assignment2.Entities.TrainerCourse>

@{
    ViewBag.Title = "AllTrainersCourses";
}

    <h2>All trainers per course</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Course title
        </th>
        <th>
            Trainers
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.GroupBy(x => x.Course))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Key.Title)
            </td>
            <td>
                <ol>
                    @foreach (var trainerCourse in item.Key.TrainerCourses.ToList())
                    {
                        <li>@trainerCourse.Trainer.FirstName @trainerCourse.Trainer.LastName</li>
                    }
                </ol>
            </td>
        </tr>
    }

</table>